name: Reset Badges

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

{% import '.github/workflows/ci-cd.yml' as ci with context %}{# Use some Jinja macros -#}

jobs:
  reset:
    name: Reset badges in documentation pages
    runs-on: ubuntu-latest

    steps:

      {{ ci.checkout() }}

      - name: Checkout docs/pages
        if: {{"${{ github.ref == 'refs/heads/main' }}"}}
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages

      - name: Generate badges on failure state
        if: {{"${{ github.ref == 'refs/heads/main' }}"}}
        run: python3 ci/make_badges.py create pages

      - name: Push to report repo
        if: {{"${{ github.ref == 'refs/heads/main' }}"}}
        run: |
          set -xe
          # Commit.
          cd pages
          git add badges
          if ! git diff --cached --quiet; then # check if there are changes
              git config user.name "${GITHUB_ACTOR}"
              git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              git commit -m "reset badges to failure state"
              git push
          fi
