# src/mcsas3/cli_tools.py

from pathlib import Path

import pandas as pd
import yaml
from attrs import define, field, validators

from . import mc_plot, workflows
from .mc_analysis import McAnalysis


def _validate_existing_file(_instance, attribute, value: Path) -> None:
    if not value.exists():
        raise FileNotFoundError(f"{attribute.name} file {value} must exist")


def _validate_yaml_file(_instance, attribute, value: Path) -> None:
    _validate_existing_file(_instance, attribute, value)
    if value.suffix != ".yaml":
        raise ValueError(f"{attribute.name} file must be a yaml file and end in .yaml")


@define
class McSAS3_cli_optimize(object):
    """Runs the McSAS optimizer (only) from the command line arguments"""

    dataFile: Path = field(kw_only=True, validator=validators.instance_of(Path))
    resultFile: Path = field(kw_only=True, validator=validators.instance_of(Path))
    readConfigFile: Path = field(kw_only=True, validator=[validators.instance_of(Path), _validate_yaml_file])
    runConfigFile: Path = field(kw_only=True, validator=[validators.instance_of(Path), _validate_yaml_file])
    resultIndex: int = field(kw_only=True, validator=[validators.instance_of(int)])
    deleteIfExists: bool = field(kw_only=True, validator=[validators.instance_of(bool)])
    nThreads: int = field(kw_only=True, validator=[validators.instance_of(int)])

    @dataFile.validator
    def fileExists(self, attribute, value):
        _validate_existing_file(self, attribute, value)

    # init is auto-generated by attrs!!!
    def __attrs_post_init__(self):
        self.run()

    def run(self):
        # remove any prior results file:
        if self.resultFile.is_file():
            # only remove result file if it is not the main file!
            # This way, you can add McSAS to an existing nexus file
            if (self.resultFile != self.dataFile) & (self.deleteIfExists):
                self.resultFile.unlink()
        # read the configuration file
        with open(self.readConfigFile, "r") as f:
            readDict = yaml.safe_load(f) or {}
        processing = workflows.prepare_1d_processing_data_from_file(
            self.dataFile,
            result_index=self.resultIndex,
            **readDict,
        )
        # read the configuration file
        with open(self.runConfigFile, "r") as f:
            optDict = yaml.safe_load(f) or {}
        if self.nThreads > 0:
            optDict["nCores"] = self.nThreads
        processing_metadata = dict(readDict)
        processing_metadata["filename"] = self.dataFile
        workflows.optimize_processing_data(
            processing,
            self.resultFile,
            result_index=self.resultIndex,
            processing_metadata=processing_metadata,
            seed=None,
            **optDict,
        )


@define
class McSAS3_cli_histogram(object):
    """Runs the McSAS histogrammer (only) from the command line arguments"""

    resultFile: Path = field(kw_only=True, validator=validators.instance_of(Path))
    histConfigFile: Path = field(kw_only=True, validator=[validators.instance_of(Path), _validate_yaml_file])
    resultIndex: int = field(kw_only=True, validator=[validators.instance_of(int)])

    def __attrs_post_init__(self):
        self.run()

    def run(self):
        # read the configuration file

        # load the data
        processing = workflows.load_result_processing_data(self.resultFile, result_index=self.resultIndex)

        # read the configuration file
        with open(self.histConfigFile, "r") as f:
            histRanges = pd.DataFrame(list(yaml.safe_load_all(f)))
        # run the Monte Carlo method
        mcres = McAnalysis(
            self.resultFile,
            processing,
            histRanges,
            store=True,
            resultIndex=self.resultIndex,
        )

        # plotting:
        # plot the histogram result
        mp = mc_plot.McPlot()
        # output file for plot:
        saveHistFile = self.resultFile.with_suffix(".pdf")
        if saveHistFile.is_file():
            saveHistFile.unlink()
        mp.resultCard(mcres, saveHistFile=saveHistFile)
