#!/usr/bin/env python3
"""Generate a Mermaid dependency diagram for internal McSAS3 modules."""

from __future__ import annotations

import ast
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "src" / "mcsas3"
OUTPUT_PATH = ROOT / "design_documentation" / "generated_module_dependencies.md"

LAYER_ORDER = (
    "Public API and entry points",
    "Canonical data and workflow layer",
    "Optimization and analysis core",
    "Other internal modules",
)

LAYER_MEMBERS = {
    "Public API and entry points": {
        "__init__",
        "__main__",
        "cli_tools",
        "mc_plot",
        "mcsas3_cli_histogrammer",
        "mcsas3_cli_runner",
        "workflows",
    },
    "Canonical data and workflow layer": {
        "data_adapters",
        "data_model",
        "ingestion",
        "mc_hdf",
        "optimizer_input",
        "preprocessing",
    },
    "Optimization and analysis core": {
        "mc_analysis",
        "mc_core",
        "mc_hat",
        "mc_model",
        "mc_model_histogrammer",
        "mc_opt",
        "osb",
    },
}


def discover_modules() -> dict[str, Path]:
    """Return the top-level Python modules that make up the McSAS3 package."""

    return {path.stem: path for path in sorted(PACKAGE_DIR.glob("*.py"))}


def resolve_local_dependency(import_name: str, local_modules: set[str]) -> str | None:
    """Map an import target to a local top-level module when possible."""

    if import_name.startswith("mcsas3."):
        candidate = import_name.split(".", maxsplit=2)[1]
    else:
        candidate = import_name.split(".", maxsplit=1)[0]
    return candidate if candidate in local_modules else None


def parse_local_dependencies(module_name: str, module_path: Path, local_modules: set[str]) -> set[str]:
    """Parse a module and collect imports that point to local McSAS3 modules."""

    tree = ast.parse(module_path.read_text(encoding="utf-8"), filename=str(module_path))
    dependencies: set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                dependency = resolve_local_dependency(alias.name, local_modules)
                if dependency is not None and dependency != module_name:
                    dependencies.add(dependency)
        elif isinstance(node, ast.ImportFrom):
            if node.level > 0:
                if node.module:
                    dependency = resolve_local_dependency(node.module, local_modules)
                    if dependency is not None and dependency != module_name:
                        dependencies.add(dependency)
                else:
                    for alias in node.names:
                        dependency = resolve_local_dependency(alias.name, local_modules)
                        if dependency is not None and dependency != module_name:
                            dependencies.add(dependency)
            elif node.module is not None:
                dependency = resolve_local_dependency(node.module, local_modules)
                if dependency is not None and dependency != module_name:
                    dependencies.add(dependency)

    return dependencies


def module_layer(module_name: str) -> str:
    """Return the display layer used for a module in the diagram."""

    for layer_name, members in LAYER_MEMBERS.items():
        if module_name in members:
            return layer_name
    return "Other internal modules"


def mermaid_node_id(module_name: str) -> str:
    """Return a Mermaid-safe node identifier."""

    return f"module_{module_name.replace('-', '_').replace('.', '_')}"


def generate_markdown() -> str:
    """Generate the dependency diagram markdown."""

    modules = discover_modules()
    local_modules = set(modules)
    dependencies = {
        module_name: parse_local_dependencies(module_name, module_path, local_modules)
        for module_name, module_path in modules.items()
    }
    layer_to_modules: dict[str, list[str]] = defaultdict(list)
    for module_name in modules:
        layer_to_modules[module_layer(module_name)].append(module_name)
    for module_names in layer_to_modules.values():
        module_names.sort()

    lines: list[str] = [
        "# McSAS3 Module Dependency Diagram",
        "",
        f"Generated on: {date.today().isoformat()}",
        "",
        "This file is generated by `python tools/generate_dependency_diagram.py`.",
        "It captures imports between top-level modules in `src/mcsas3` and is intended as a",
        "maintained structure overview rather than a full call graph.",
        "",
        "```mermaid",
        "flowchart LR",
    ]

    class_members: dict[str, list[str]] = defaultdict(list)
    class_members["public"] = []
    class_members["canonical"] = []
    class_members["core"] = []
    class_members["other"] = []
    class_name_for_layer = {
        "Public API and entry points": "public",
        "Canonical data and workflow layer": "canonical",
        "Optimization and analysis core": "core",
        "Other internal modules": "other",
    }

    for layer_name in LAYER_ORDER:
        modules_in_layer = layer_to_modules.get(layer_name, [])
        if not modules_in_layer:
            continue
        lines.append(f'  subgraph {mermaid_node_id(layer_name)}["{layer_name}"]')
        for module_name in modules_in_layer:
            node_id = mermaid_node_id(module_name)
            lines.append(f'    {node_id}["{module_name}"]')
            class_members[class_name_for_layer[layer_name]].append(node_id)
        lines.append("  end")

    for module_name in sorted(dependencies):
        source_id = mermaid_node_id(module_name)
        for dependency in sorted(dependencies[module_name]):
            target_id = mermaid_node_id(dependency)
            lines.append(f"  {source_id} --> {target_id}")

    lines.extend(
        [
            "  classDef public fill:#e7f0ff,stroke:#3a66b3,color:#1d2b45;",
            "  classDef canonical fill:#e8f8ee,stroke:#2a7f45,color:#153523;",
            "  classDef core fill:#fff2df,stroke:#b06a00,color:#4d3200;",
            "  classDef other fill:#f2f2f2,stroke:#777777,color:#333333;",
        ]
    )

    for class_name, node_ids in class_members.items():
        if node_ids:
            lines.append(f"  class {','.join(node_ids)} {class_name};")

    lines.extend(
        [
            "```",
            "",
            "## Regeneration",
            "",
            "Run:",
            "",
            "```bash",
            "./.venv/bin/python tools/generate_dependency_diagram.py",
            "```",
            "",
            "## Notes",
            "",
            "- The diagram is generated from import statements, so it shows module coupling rather "
            "than runtime call flow.",
            "- External dependencies are intentionally omitted.",
            "- The layer grouping is curated for readability; edges within and across layers remain generated.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the generated dependency diagram to the tracked markdown file."""

    OUTPUT_PATH.write_text(generate_markdown(), encoding="utf-8")


if __name__ == "__main__":
    main()
