name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # make a new version first, release or prerelease
  release:
    uses: ./.github/workflows/release.yml

  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: [release, tests]  # build only if all tests are successful
    uses: ./.github/workflows/build.yml
    secrets: inherit

  docs:
    needs: [release]  # get (release) version number first
    uses: ./.github/workflows/docs.yml

  coverage:
    needs: [tests, docs]  # coverage report is added to the docs webpage
    uses: ./.github/workflows/coverage.yml
