name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # check if everything works first
  tests:
    uses: ./.github/workflows/tests.yml

  # make a new version next, release or prerelease
  release:
    needs: [tests]
    uses: ./.github/workflows/release.yml

  build:
    needs: [release, tests]  # build only if all tests are successful
    uses: ./.github/workflows/build.yml
    secrets: inherit

  docs:
    needs: [release]  # get (release) version number first
    uses: ./.github/workflows/docs.yml

  coverage:
    needs: [tests, docs]  # coverage report is added to the docs webpage
    uses: ./.github/workflows/coverage.yml

  publish:  # needs to be in the top-level .yml for Trusted Publishing to work @pypi
    needs: [build,docs,coverage]
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies
        shell: sh
        run: |
          [ -d "/c/miniconda" ] && /c/miniconda/condabin/activate.bat
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          merge-multiple: true
          path: dist

      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
