name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  testing:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.10']

      runs-on: ${{ matrix.os }}

      steps:
      - name: Checkout sasmodels
        uses: actions/checkout@v3
        with:
          repository: SasView/sasmodels
          path: sasmodels

      - name: Show the resulting dir structure
        run: pwd; ls -la; ls -la sasmodels

      - uses: actions/checkout@v3
        with:
          path: mcsas3

      - name: Show the resulting dir structure
        run: pwd; ls -la

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install opencl-headers ocl-icd-opencl-dev libpocl2

      - name: Install Python packages
      # from https://github.com/SasView/sasmodels/blob/master/.github/workflows/test.yml
      # with extensions for mcsas3
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel setuptools
          python3 -m pip install mako
          python3 -m pip install numpy scipy matplotlib pandas h5py pyyaml pytest bumps unittest-xml-reporting tinycc
          python3 -m pip install pyopencl

      - name: Run pytest
        run: |
          cd mcsas3
          export PYTHONPATH=../sasmodels
          # ignore time (and computation) extensive tests, which will be throttled massively on github
          pytest -v --ignore=sasmodels --durations=30 \
            -k 'not 1D_mcsas_sphere_and_rehistogrammer and not 1D_sphere_accuratestate and not 1D_sim0_singlecore and not 1D_sim1_multicore and not 1D_sim2_histogram'

# vim: set ts=2 sts=2 sw=2 tw=0 et:
